create table category (id bigint not null auto_increment, image longblob, name varchar(255), primary key (id)) engine=InnoDB;
create table customer (id bigint not null auto_increment, email varchar(255), first_name varchar(255), last_name varchar(255), phone_number varchar(255), address varchar(255), city varchar(255), country varchar(255), zipcode integer not null, primary key (id)) engine=InnoDB;
create table images (id bigint not null auto_increment, image longblob, product_id bigint, primary key (id)) engine=InnoDB;
create table order_product (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders (id bigint not null auto_increment, date_ordered date, order_number varchar(255), status varchar(255), quantities integer not null, total_price float not null, customer_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table privilege (id bigint not null auto_increment, privilege varchar(255), primary key (id)) engine=InnoDB;
create table products (id bigint not null auto_increment, brand varchar(255), description longtext, in_stock integer not null, name varchar(255), price float not null, category_id bigint, primary key (id)) engine=InnoDB;
create table role_privilege (role_id bigint not null, privilege_id bigint not null) engine=InnoDB;
create table roles (id bigint not null auto_increment, role varchar(255), primary key (id)) engine=InnoDB;
create table shopping_cart (id bigint not null auto_increment, quantity integer, subtotal_price float, product_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_role (user_id bigint not null, role_id bigint not null) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(255), first_name varchar(255), last_name varchar(255), phone_number varchar(255), password varchar(255), reg_date date, user_name varchar(255), primary key (id)) engine=InnoDB;
alter table images add constraint FKghwsjbjo7mg3iufxruvq6iu3q foreign key (product_id) references products (id);
alter table order_product add constraint FKo6helt0ucmegaeachjpx40xhe foreign key (product_id) references products (id);
alter table order_product add constraint FKl5mnj9n0di7k1v90yxnthkc73 foreign key (order_id) references orders (id);
alter table orders add constraint FK624gtjin3po807j3vix093tlf foreign key (customer_id) references customer (id);
alter table orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table products add constraint FK1cf90etcu98x1e6n9aks3tel3 foreign key (category_id) references category (id);
alter table role_privilege add constraint FKdkwbrwb5r8h74m1v7dqmhp99c foreign key (privilege_id) references privilege (id);
alter table role_privilege add constraint FKoyen4wwrw6fh56dy3ri05may1 foreign key (role_id) references roles (id);
alter table shopping_cart add constraint FK26ajdolmyw3a95bhn6pjk5dor foreign key (product_id) references products (id);
alter table shopping_cart add constraint FKr1irjigmqcpfrvggavnr7vjyv foreign key (user_id) references users (id);
alter table user_role add constraint FKt7e7djp752sqn6w22i6ocqy6q foreign key (role_id) references roles (id);
alter table user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users (id);
